name: Docker images

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/loomio:"${{ github.sha }}" .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/loomio:"${{ github.sha }}" ${{ secrets.DOCKERHUB_USERNAME }}/loomio:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loomio:"${{ github.sha }}"
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/loomio:latest
